---
title: "Quick Introduction to timelineR"
author: "Kenton Russell"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Quick Introduction to timelineR}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Installation

```{r eval = FALSE}
devtools::install_github("timelyportfolio/timelineR")
```

## Example

```{r}
library(timelineR)

# example with dates provided by d3.layout.timeline author
#  Elijah Meeks
#  http://bl.ocks.org/emeeks/280cb0607c68faf30bb5

t1 <- timeline(
  read.csv("http://bl.ocks.org/emeeks/raw/280cb0607c68faf30bb5/wars.csv"),
  colorScale = htmlwidgets::JS(
'd3.scale.ordinal()
    .domain(["European","Native","Colonial","Latin America","Internal"])
    .range(["#96abb1", "#313746", "#b0909d", "#687a97", "#292014"])
'    
  ),
  color = "sphere",
  height = "400",
  width = "80%"
)
 
t1
```

### Add an Axis

```{r}
add_axis(t1)
```

### Customize

```{r}
# use this example as inspiration
#   http://jasonheppler.org/projects/war/

library(pipeR)

t1 %>>%
  add_axis(tickSize = 400) %>>%
  add_tasks(
    htmlwidgets::JS(
'
function(){
  var svg = d3.select(this.el).select("svg");
  svg.selectAll(".timeline-axis > path")
    .style("fill","none")
    .style("stroke","none");
  svg.selectAll(".timeline-axis .tick line")
    .style("stroke","gray")
    .attr("stroke-dasharray","5 5");
  svg.selectAll("rect")
    .style("stroke","white")
    .attr("rx",4);
}
'
    )
  )
```
